Feature/k8s
danskernesdigitalebibliotek/ddb-follow-searches pull request #1
Opened 2020-06-25 08:25 UTC by cableman

2020-07-08 07:32 UTC, kasperg reviewed
Remember to remove parts of the old deployment setup.

This includes:

- [Github workflows for deployment](https://github.com/danskernesdigitalebibliotek/ddb-follow-searches/blob/feature/k8s/.github/workflows/push.yml#L92-L120)
- [Parts](https://github.com/danskernesdigitalebibliotek/ddb-follow-searches/blob/master/Envoy.blade.php) [of](https://github.com/danskernesdigitalebibliotek/ddb-follow-searches/blob/master/composer.json#L35) the old deployment setup using Envoy.
- [Documentation referring to the old deployment setup](https://github.com/danskernesdigitalebibliotek/ddb-follow-searches#server-setup)

2020-10-27 10:54 UTC, kasperg requested changes
My comments regarding danskernesdigitalebibliotek/ddb-material-list#1 also apply here.

Also see my previous comment about removing [parts](https://github.com/danskernesdigitalebibliotek/ddb-follow-searches/blob/master/Envoy.blade.php) [of](https://github.com/danskernesdigitalebibliotek/ddb-follow-searches/blob/master/composer.json#L35) the old deployment setup using Envoy.

2020-10-27 12:27 UTC, kasperg commented
The specification test failure is not related to this PR. It will be fixed when #4 is merged.

2020-10-27 20:51 UTC, cableman commented
Updated the code with changes from this review and the one for material list.

I regard to en Envoy it seams to be an integrated part of the Larvel and as I don't known anything about Larvel I think you should make another PR removing it. It do not seam to block anything here.

2020-10-28 14:01 UTC, kasperg reviewed
> I regard to en Envoy it seams to be an integrated part of the Larvel and as I don't known anything about Larvel I think you should make another PR removing it. It do not seam to block anything here.

It is a Composer package and a configuation file that needs to be removed. I linked to the parts in my comment. I have removed them it a commit added to the PR in a25939d.

2020-10-28 14:01 UTC, kasperg commented on .github/workflows/pull_request.yml
> +          version: v3.3.4
Same quibbles are for material list regarding versioning.

2020-10-28 20:27 UTC, merged